version: '2.4'

x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/task?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_USERNAME`: root
  SPRING_DATASOURCE_PASSWORD: root

services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - task_data:/var/lib/mysql
    mem_limit: 512m

  stefanini-tech-test:
    image: patrickviolin/stefanini-newm-todo-list:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
        <<: *database-variables
    mem_limit: 512m

volumes:
  task_data: