server:
  error:
    include-stacktrace: on_param
  servlet:
    context-path:
  tomcat:
    relaxed-query-chars: '|,{,},[,]'

spring:
  application:
    name: stefanini-newm-todo-list
  datasource:
    url: jdbc:mysql://localhost:3306/task?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update